apiVersion: v1
entries:
  guacamole-stack:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-22T13:59:36.9101556+02:00"
    description: A Helm chart for Kubernetes
    digest: 7ec2e869d59a98fa224234eb43232662121bde42c828c8b55428c673227ef440
    name: guacamole-stack
    type: application
    urls:
    - guacamole-stack-0.1.0.tgz
    version: 0.1.0
  image-viewer:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-22T13:59:36.9164761+02:00"
    description: Helm Chart 4 Image Viewer Demo App
    digest: 4f1904cf4cae0b99c834fe60c437212e25969cce4c84a05660da5dbea7bb1df1
    name: image-viewer
    type: application
    urls:
    - image-viewer-0.1.1.tgz
    version: 0.1.1
generated: "2023-05-22T13:59:36.9090859+02:00"
