{{- if and (.Values.backend.messageBus.include) (eq .Values.stackMode "microservices") -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-ss
  labels:
    {{- include "image-viewer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: rabbitmq-ss
  serviceName: {{ .Values.services.messageBus.name | default "message-bus" }}
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-ss
    spec:
      serviceAccountName: {{ include "image-viewer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: rabbitmq
        image: {{ .Values.services.messageBus.image | default "rabbitmq:3-management" }}
        ports:
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 15672
          name: webui
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "400m"
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.services.messageBus.rabbitMqUser | default "rabbitmq" }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.services.messageBus.rabbitMqPassword | default "rabbitmq" }}
 
{{- end }}