{{- range $ep := .Values.reverseEndpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $.Values.resourcePrefix }}{{ $ep.name }}
subsets:
  - addresses:
{{- range $ip := $ep.ips }}
      - ip: {{ $ip }}
{{- end }}
    ports: 
      - port: {{ $ep.port }}
---
{{- end }}